### ISSUE TITLE
Sort by file size

### ISSUE THREAD

**Issue by ianshmean** [drewminns/slackdeletron#19]
Sorting by file size would be very helpful. Especially sorting across multiple pages (although I can appreciate that might be harder if the api doesn't have a sort function built in)

**Comment by drewminns** [comment]
Hmmm, it should be there on the top right? 

<img width="307" alt="screen shot 2018-05-08 at 10 34 34 am" src="https://user-images.githubusercontent.com/448452/39763576-8590abf6-52ab-11e8-9b0a-a58e93f0509a.png">

**Comment by ianshmean** [comment]
My bad! Missed that

**Comment by drewminns** [comment]
Good to note! Might need some UI updates! Thanks
