### ISSUE TITLE
Enable https

### ISSUE THREAD

**Issue by ianshmean** [drewminns/slackdeletron#20]
Given the nature of the data being shared, and how https has been rolled out, it seems necessary.

btw, thanks for building this!

**Comment by drewminns** [comment]
Should be coming soon. I initially launched on Heroku and have found it not easy to handle DNS shenanigans so it's on it's way to AWS with SSL now.

Will close this when it's working alright 😄

**Comment by drewminns** [comment]
Done! HTTPS is alive!!!
