### ISSUE TITLE
Private channels won't appear in the list of channels

### ISSUE THREAD

**Issue by boisei0** [drewminns/slackdeletron#27]
Because of the missing permission `groups.list` private channels don't appear in the list of channels, thus files uploaded in there can't be deleted using deletron.

**Comment by suntehnik** [comment]
missing this feature

**Comment by pensierinmusica** [comment]
+1

**Comment by drewminns** [comment]
Updated in latest release!

**Comment by drewminns** [comment]
Reopening because some users were experiencing issues. Will confirm with test deploy I'll post here.

**Comment by drewminns** [comment]
So it looks like I've added the permission but it seems to not be applying to the tokens provided. I've reached out to Slack about next steps and will keep everyone updated!

<img width="951" alt="screen shot 2018-06-05 at 8 41 17 am" src="https://user-images.githubusercontent.com/448452/40976730-070688de-689d-11e8-91b9-cfaad4a2c600.png">
<img width="772" alt="screen shot 2018-06-05 at 8 41 45 am" src="https://user-images.githubusercontent.com/448452/40976731-0713ef6a-689d-11e8-94f4-303bac59542f.png">

**Comment by drewminns** [comment]
Updated and deployed!
