### ISSUE TITLE
[Hosted slackdeletron] connecting to http does not redirect to the https version

### ISSUE THREAD

**Issue by boisei0** [drewminns/slackdeletron#28]
When connecting to http://slackdeletron.com, instead of giving a 301 permanently moved to https://www.slackdeletron.com, a html file is server that instead wraps the https version in an iframe. Not only is this not secure, but since https://www.slackdeletron.com/ has SAMEORIGIN as X-Frame-Options returned, the logging in to slack will fail.

**Comment by drewminns** [comment]
Updated and express redirect added!

**Comment by boisei0** [comment]
I'd like to point out that it this point it's a deployment issue, rather than an issue with the code. Adding middleware for redirection will work if the application is run as standalone, hosted directly as is. It is however deployed behind nginx, and nginx takes care of redirecting from URL to the correct part of the application. So in order to fix it in the version that you are hosting, the nginx configuration has to be changed to make port 80 with server `slackdeletron.com` redirect to the https://www version on port 443. Don't just redirect it to port 443 with the same address, as  https://slackdeletron.com/ is an option too, but right nginx just drops the connection when trying to access that one.

**Comment by boisei0** [comment]
@drewminns any thought on the previous? It's still happening since it's a deployment issue, and every time our free workspace runs out of space I've to write an essay on how only that specific link works and won't give white screens for http/https mixing of content blocked by browsers. But since "slackdeletron.com" is known by all the users, but actually using just that or have slacky create a link from it based on just that name, will go wrong as it gives the white screen version.
