### ISSUE TITLE
White page when trying to authorise app

### ISSUE THREAD

**Issue by danieltj27** [drewminns/slackdeletron#34]
When I click the button to connect Slack Deletron to Slack it redirects to the same page but doesn't load anything (white page). I have to manually go to `http://www.slackdeletron.com/auth/slack` for it to redirect properly.

**Comment by danieltj27** [comment]
Hmm, it seems to be working now but from looking at my browsing history, I think it sent me to `HTTP`.

**Comment by drewminns** [comment]
Interesting. I'll confirm the redirect URI in the Slack configuration.
