### ISSUE TITLE
Get files button doesn't load any files

### ISSUE THREAD

**Issue by danieltj27** [drewminns/slackdeletron#35]
I've got a fair few files shared in my workspace, but when I click the button to `Get Files`, nothing happens. It stays on the congratulations message when no files can be retrieved even when changing the filters down the left side menu.

**Comment by danieltj27** [comment]
The request URI was:

```
https://slack.com/api/files.list?token=XYZ&user=XYZ&page=1&types=&channel=
```

The response sent back from that was:

```
{"ok":true,"files":[],"paging":{"count":100,"total":0,"page":1,"pages":0}}
```

Which is definitely wrong because I've got a lot more files than 0. It's verifying the correct workspace as well, so it's not like it's going to a team with no files.

Thanks for making Slack Deletron anyway, very handy.

**Comment by drewminns** [comment]
hmmmm, and if you put the URI into the browser, you receive the same response?

This may be an issue on the Slack end, but I would love to see if we can debug it.

**Comment by TomThorpe** [comment]
Hi, I have the same problem with the deployment on slackdeletron.com but I think it's related to #25 .

If I look at the network request its making it's getting zero results. If I then drop off the `&channel=` on the request (or I pick a channel), it seems to work. Do you notice the same @danieltj27 ?

If so hopefully a new deployment of the fix after #25 should also fix this?

**Comment by drewminns** [comment]
Removed the empty channel param in latest release. Hoping it works!

**Comment by danieltj27** [comment]
It's not working if I do everything in all channels, but all images in a specific channel seems to work.

**Comment by drewminns** [comment]
Tried another deploy. Should be running now! Param is not included if empty!

**Comment by danieltj27** [comment]
It works now, thanks @drewminns 😄
