### ISSUE TITLE
Cant sign in

### ISSUE THREAD

**Issue by mike-gracia** [drewminns/slackdeletron#42]
Hey I am trying to get started with this and when I try to sign in I get redirected back to localhost:8081 with ?Code=###&state= appended to the url. Any ideas? Do I need something like Ngrok for https, this is my first time messing with oauth.

**Comment by drewminns** [comment]
Hey! I made some changes to the 'Running Locally' area of the readme. Hopefully it helps. https://github.com/drewminns/slackdeletron#running-locally

Of course, let me know if there's any other troubles!

**Comment by mike-gracia** [comment]
Got it working, thanks!

**Comment by drewminns** [comment]
Great! Thanks for pulling it down! Have fun and let me know if you have other questions!
