### ISSUE TITLE
Deletron Install Issue

### ISSUE THREAD

**Issue by tomjames1990** [drewminns/slackdeletron#44]
Hello,

I got our workspace owner to install and approve Deletron.

But when i go to run it this error still comes up:

Apologies, but Slack Deletron can’t be installed.
This app isn’t listed in the Slack App Directory, so only workspace owners can install it.

Does it take some time after the app getting approved to install before it will work?

Or do you have any other suggestions?

Thanks

**Comment by drewminns** [comment]
Hi there,

I'm not too sure. It's possible that the permissions that the app requires are blocked by the admin as well? In this case, it's a bit in Slack's hands.

Sorry I can't be more helpful but I'll do some digging!

**Comment by tomjames1990** [comment]
Not a problem, was hoping it was a common issue!

Thank you for your help.
